### ISSUE TITLE
Binaries for rchdman

### ISSUE THREAD

**Issue by bUbblE1968** [SnowflakePowered/chd-rs#5]
subj

**Comment by chyyran** [comment]
Do you mean for rchdman? Its fairly incomplete and I would still recommend using the MAME chdman but I don’t see why binaries couldnt be provided.

**Comment by chyyran** [comment]
If you mean compression, there are no plans currently but no particular blockers API-wise if its implemented in the future.

**Comment by chyyran** [comment]
rchdman is super barebones right now, so I don't want to release binaries until #6 is done.

**Comment by chyyran** [comment]
I honestly don't know why this would be preferred over `chdman` but here it is.

https://github.com/SnowflakePowered/chd-rs/releases/tag/rchdman-0.1.0
