### ISSUE TITLE
Maybe i'm being paranoid but this code looks somewhat wrong

### ISSUE THREAD

**Issue by i30817** [SnowflakePowered/chd-rs#9]
https://github.com/SnowflakePowered/chd-rs/blob/1e09072d60a6874fc8169addf47eecfb374c5636/chd-rs/src/chdfile.rs#L54

in that it's a tautology that it's false

https://github.com/SnowflakePowered/chd-rs/blob/1e09072d60a6874fc8169addf47eecfb374c5636/chd-rs/src/chdfile.rs#L58

and the second line is suspect too, one is using the field the other the method.

If there is a weird reason for this to be correct, please tell me for my peace of mind.

I suspect it was meant to be `if p.header().sha1() != header.parent_sha1()` and `if p.header().sha1() != header.parent_md5()`?

**Comment by chyyran** [comment]
No, good catch this is a bug.

Fixed in https://github.com/SnowflakePowered/chd-rs/commit/858dc16f32d9068c38a420e53909a8aeb198bbca (0.2.1)
